In [1]:
import numpy as np

In [77]:
Nqub = 2
AdjMatrixGraph = [[0,1],[1,0]]
#Nqub = 3
#AdjMatrixGraph = [[0,1,1],[1,0,1],[1,1,0]]

string = 'IXYAB' #A is XY, B is YY
if Nqub > 3 and Nqub < 6:
  string = string+'CD'#C for second XY, D for second YY
if Nqub >= 6:
  string = string+'EF'#E for third XY, F for third YY

In [78]:
def toString(List): 
    return ''.join(List) 

arr = []
def allLexicographicRecur (string, data, last, index): 
    length = len(string) 
    for i in range(length): 
        data[index] = string[i] 
        if index==last: 
            arr.append(toString(data))
        else: 
            allLexicographicRecur(string, data, last, index+1) 
  
def allLexicographic(string, length_required): 
    length = length_required

    data = [""] * (length+1) 

    string = sorted(string) 
    allLexicographicRecur(string, data, length-1, 0)
allLexicographic(string, Nqub) 
print(arr)


['AA', 'AB', 'AI', 'AX', 'AY', 'BA', 'BB', 'BI', 'BX', 'BY', 'IA', 'IB', 'II', 'IX', 'IY', 'XA', 'XB', 'XI', 'XX', 'XY', 'YA', 'YB', 'YI', 'YX', 'YY']


In [79]:

# ith entry in the string corresponds to ith qubit
def find(s, ch):
    return [i for i, ltr in enumerate(s) if ltr == ch]

def validate_string(string, Graph):
  # Number of As, Bs, Cs, Ds, Es, Fs are even
  # AA, BB, ... should be between qubits that are connected in the graph
  # CD can exist only if AB exist
  # EF can exist only if both AB and CD exist
  if (string.count('A') > 2) or (string.count('B') > 2) or (string.count('C') > 2) or (string.count('D') > 2) or (string.count('E') > 2) or (string.count('F') > 2):
    return False
  if (string.count('A')%2 != 0) or (string.count('B')%2 != 0) or (string.count('C')%2 != 0) or (string.count('D')%2 != 0) or (string.count('E')%2 != 0) or (string.count('F')%2 != 0):
    return False
  if ('C' in string) and ('A' not in string):
    return False
  if ('E' in string) and (('A' not in string) or ('C' not in string)):
    return False
  if ('D' in string) and ('B' not in string):
    return False
  if ('F' in string) and (('B' not in string) or ('D' not in string)):
    return False
  
  if 'A' in string:
    idx = find(string, 'A')
    if Graph[idx[0]][idx[1]] != 1:
      return False
  if 'B' in string:
    idx = find(string, 'B')
    if Graph[idx[0]][idx[1]] != 1:
      return False
  if 'C' in string:
    idx = find(string, 'C')
    if Graph[idx[0]][idx[1]] != 1:
      return False
  if 'D' in string:
    idx = find(string, 'D')
    if Graph[idx[0]][idx[1]] != 1:
      return False
  if 'E' in string:
    idx = find(string, 'E')
    if Graph[idx[0]][idx[1]] != 1:
      return False
  if 'F' in string:
    idx = find(string, 'F')
    if Graph[idx[0]][idx[1]] != 1:
      return False
  return True

In [80]:
final_arr = []
for i in arr:
  if validate_string(i, AdjMatrixGraph):
    final_arr.append(i)
print(final_arr)

['AA', 'BB', 'II', 'IX', 'IY', 'XI', 'XX', 'XY', 'YI', 'YX', 'YY']


In [81]:
# I, sigx, sigy, sigz
arr = []
allLexicographic('IXYZ', Nqub) 
for i in range(len(arr)):
  arr[i] = arr[i][:Nqub]
val = ''
mu = [i for i in list(dict.fromkeys(arr)) if i != val]
print((mu))

arr = []
allLexicographic('IZ', Nqub) 
for i in range(len(arr)):
  arr[i] = arr[i][:Nqub]
val = ''
z_basis = [i for i in list(dict.fromkeys(arr)) if i != val]
print((z_basis))

['II', 'IX', 'IY', 'IZ', 'XI', 'XX', 'XY', 'XZ', 'YI', 'YX', 'YY', 'YZ', 'ZI', 'ZX', 'ZY', 'ZZ']
['II', 'IZ', 'ZI', 'ZZ']


In [82]:
def single_qub_meas(b, mu):
  if b=='X':
    if (mu == 'Z'):
      return 'Y', 1
    elif (mu == 'Y'):
      return 'Z', -1
    else:
      return b, 1
  elif b=='Y':
    if (mu == 'Z'):
      return 'X', 1
    elif (mu == 'X'):
      return 'Z', 1
    else:
      return b, 1
  elif b=='Z':
    if (mu == 'X'):
      return 'Y', 1
    elif (mu == 'Y'):
      return 'X', 1
    else:
      return b, 1
  else:
    return b, 1

def two_qub_meas(b1, b2, mu):
  if mu == 'A' or mu == 'C' or mu == 'E':
    if (b1=='X' and b2=='X'):
      return 'I', 'Z', -1
    elif (b1=='Y' and b2=='Y'):
      return 'Z', 'I', 1
    elif (b1=='I' and b2=='I') or (b1=='Z' and b2=='Z'):
      return b1, b2, 1
    else:
      return 'X', 'Y', 1
  if mu == 'B' or mu == 'D' or mu == 'F':
    if (b1=='X' and b2=='Y') or (b1=='Y' and b2=='X'):
      return 'I', 'Z', -1
    elif (b1=='I' and b2=='I') or (b1=='Z' and b2=='Z'):
      return b1, b2, 1
    else:
      return 'X', 'Y', 1

def value(strB, strMu):
  out = ''
  sign = 1
  if ('A' in strB):
    idx = find(strB, 'A')
    a,b,s = two_qub_meas(strMu[idx[0]], strMu[idx[1]], 'A')
    out = out + a + b
    sign = sign*s
  if ('C' in strB):
    idx = find(strB, 'C')
    a,b,s = two_qub_meas(strMu[idx[0]], strMu[idx[1]], 'C')
    out = out + a + b
    sign = sign*s
  if ('E' in strB):
    idx = find(strB, 'E')
    a,b,s = two_qub_meas(strMu[idx[0]], strMu[idx[1]], 'E')
    out = out + a + b
    sign = sign*s
  if ('B' in strB):
    idx = find(strB, 'B')
    a,b,s = two_qub_meas(strMu[idx[0]], strMu[idx[1]], 'B')
    out = out + a + b
    sign = sign*s
  if ('D' in strB):
    idx = find(strB, 'D')
    a,b,s = two_qub_meas(strMu[idx[0]], strMu[idx[1]], 'D')
    out = out + a + b
    sign = sign*s
  if ('F' in strB):
    idx = find(strB, 'F')
    a,b,s = two_qub_meas(strMu[idx[0]], strMu[idx[1]], 'F')
    out = out + a + b
    sign = sign*s
  if ('X' in strB):
    idx = find(strB, 'X')
    for i in idx:
      v,s = single_qub_meas(strMu[i], 'X')
      out = out+ v
      sign = sign*s
  if ('Y' in strB):
    idx = find(strB, 'Y')
    for i in idx:
      v,s = single_qub_meas(strMu[i], 'Y')
      out = out+ v
      sign = sign*s
  if ('I' in strB):
    idx = find(strB, 'I')
    for i in idx:
      v,s = single_qub_meas(strMu[i], 'I')
      out = out+ v
      sign = sign*s
  if out in z_basis:
    return sign
  else:
    return 0

In [83]:
A = np.zeros((len(final_arr),len(mu)))

for i in range(len(final_arr)):
  for j in range(len(mu)):
    A[i,j] = value(final_arr[i], mu[j])

print(A)

[[ 1.  0.  0.  0.  0. -1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0. -1.  0.  0. -1.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  1.  0.]
 [ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.]
 [ 1.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  0.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.]
 [ 1. -1.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  1. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0. -1.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -1.  0.  0. -1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [84]:
print (mu)

['II', 'IX', 'IY', 'IZ', 'XI', 'XX', 'XY', 'XZ', 'YI', 'YX', 'YY', 'YZ', 'ZI', 'ZX', 'ZY', 'ZZ']


In [85]:
print(final_arr)

['AA', 'BB', 'II', 'IX', 'IY', 'XI', 'XX', 'XY', 'YI', 'YX', 'YY']


In [ ]:
# If using this on Google collab, we need to install the packages
try:
  import google.colab
  IN_COLAB = True
except:
  IN_COLAB = False

# Let's start with Pyomo
if IN_COLAB:
    !pip install -q pyomo